AWSTemplateFormatVersion: '2010-09-09'

Resources:
    MyEC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            InstanceType: t2.micro
            ImageId: ami-067d1e60475437da2
            Tags:
                - Key: Name
                  Value: MyEC2Instance
            SecurityGroups:
              - !Ref MySecurityGroup

    MySecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: MySG
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0

Outputs:
    InstanceId:
        Value: !Ref MyEC2Instance

